# Start from a jdk base image
FROM eclipse-temurin:17.0.9_9-jdk
#@sha256:ef3ab7c2888f8f2f9cc043a9f33ce3dac5e7acd0d8fe964188989234337090dc

EXPOSE 8080

# install jemalloc as alternative malloc implementation (to be more robust to memory fragmentation)
RUN apt-get update && apt-get install --yes --no-install-recommends libjemalloc2
RUN apt-get install -y libx11-6
RUN apt-get install -y tcl8.6 tk8.6

# set jemalloc as default malloc in env variable
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2

# Copy from build stage to keep image size small
COPY jars/liger.jar app.jar

# copy necessary resource files
COPY liger_resources liger_resources

# copy XLE
COPY ../xle /xle

COPY src/.bashrc /root/.bashrc

# copy grammars
COPY grammars /grammars

## ENTRYPOINT ["java", "-jar", "/app.jar"]
ENTRYPOINT exec java -jar /app.jar -web
