FROM python:3.12-slim

# Set working directory (optional but good practice)
WORKDIR /app

RUN apt-get update && apt-get install -y --fix-missing\
    gcc \
    python3-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements file and install dependencies
COPY ../Stanza/requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir --upgrade -r requirements.txt

# Copy application code
COPY ../Stanza/main.py main.py
COPY ../Stanza/stanza_models.py stanza_models.py

# Copy the Stanza models directory
COPY ../Stanza/models/ models/

# Expose the port
EXPOSE 8083

# Run the app using uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8083"]
