services:
  liger:
    build:
      dockerfile: Docker/Dockerfile-liger
      context: ..
      args:
        - platform=linux/amd64
    platform: linux/amd64
    ports:
      - '8080:8080'
  stanza:
    build:
      dockerfile: Docker/Dockerfile-stanza
      context: ..
      args:
        - platform=linux/amd64
    ports:
      - '8083:8083'
  vampire:
    build:
      dockerfile: Docker/Dockerfile-vampire
      context: ..
      args:
       - platform=linux/amd64
    platform: linux/amd64
    ports:
      - '8082:8082'
    privileged: true  # Add this to enable privileged mode
  gswb:
    build:
      dockerfile: Docker/Dockerfile-gswb
      context: ..
    ports:
      - '8081:8081'
  frontend:
    build:
      dockerfile: Docker/Dockerfile-frontend
      context: ..
    ports:
      - '80:80'
    depends_on:
        - gswb
        - liger
    restart: always


