# Use the official Python base image
FROM python:3.9

EXPOSE 8082

# Set an environment variable for the helper files
ENV BOXER_PATH="boxer"

# Install only required system dependencies (minimal setup)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates && \
    apt-get clean

# Set the working directory
WORKDIR /vampire

# Copy the pre-built Vampire binary and make it executable
COPY vampire_build/vampire /vampire/
RUN chmod +x /vampire/bin/vampire

# Optionally install Python libraries (if needed)
RUN pip install --upgrade pip
# install prolog
RUN apt-get install --yes swi-prolog
RUN pip install -U pyswip

# Copy the inference Python script and related files
COPY inference/run_vampire.py /vampire/
COPY inference/vampire_call.py /vampire/
COPY inference/vampire_models.py /vampire/

COPY inference/requirements.txt /vampire/

# Install the required Python libraries
RUN pip install -r requirements.txt

# copy boxer files to vampire
COPY BB-DRT/boxer /vampire/boxer

# COPY inference/vampire_test/xleplusglue2.p /vampire/xleplusglue2.p

# Run the sysctl command to modify kernel settings (this works only in privileged mode)
# RUN sudo sysctl -w kernel.perf_event_paranoid=-1 || echo "Ignoring sysctl failure, needs privileged mode."

# Set the command to run the Python script
#CMD ["python", "run_vampire.py"]
CMD ["uvicorn", "run_vampire:app", "--host", "0.0.0.0", "--port", "8082", "--reload"]
#CMD ["fastapi", "run", "run_vampire.py", "--port", "8082"]
#uvicorn main:app --host 0.0.0.0 --port 80