# The JAR is built outside the image, so only a runtime is needed here.
FROM eclipse-temurin:17.0.9_9-jre

EXPOSE 8081

# install jemalloc as alternative malloc implementation (to be more robust to memory fragmentation)
RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        libjemalloc2 \
        swi-prolog && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# set jemalloc as default malloc in env variable
ENV LD_PRELOAD=libjemalloc.so.2
ENV JAVA_TOOL_OPTIONS=-Xmx512m

# Copy from build stage to keep image size small
COPY jars/gswb.jar app.jar

# copy necessary resource files
COPY BB-DRT/boxer /gswb_resources/boxer
COPY BB-DRT/lambdaDRT.pl /gswb_resources/lambdaDRT.pl

## ENTRYPOINT ["java", "-jar", "/app.jar"]
ENTRYPOINT exec java -jar /app.jar -web
