# run
FROM nginx:1.17.1-alpine
# COPY nginx.conf /etc/nginx/nginx.conf
COPY frontend/xleplusglue-client /usr/share/nginx/html

# Copy the custom nginx config
COPY frontend/nginx.conf /etc/nginx/nginx.conf