# Start from a jdk base image
FROM eclipse-temurin:17.0.9_9-jdk

EXPOSE 8080

# install jemalloc as alternative malloc implementation (to be more robust to memory fragmentation)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libjemalloc2 \
        libx11-6 \
        tcl8.6 \
        tk8.6 \
        swi-prolog && \
    apt-get clean

# set jemalloc as default malloc in env variable
ENV LD_PRELOAD=libjemalloc.so.2

COPY BB-DRT/boxer /liger_resources/boxer
COPY BB-DRT/lambdaDRT.pl /liger_resources/lambdaDRT.pl

# Copy from build stage to keep image size small
COPY jars/liger.jar app.jar

# copy necessary resource files
COPY liger_resources liger_resources

# copy XLE
COPY ../xle /xle

COPY src/.bashrc /root/.bashrc

# copy grammars
COPY grammars /grammars

## ENTRYPOINT ["java", "-jar", "/app.jar"]
ENTRYPOINT exec java -jar /app.jar -web
